"""rename_fanza_id_to_content_id

Revision ID: e9d2e36472ae
Revises: sync_models_to_db
Create Date: 2026-05-13 05:02:20.474967+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9d2e36472ae'
down_revision: Union[str, None] = 'sync_models_to_db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actresses', sa.Column('content_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_actresses_fanza_id'), table_name='actresses')
    op.create_index(op.f('ix_actresses_content_id'), 'actresses', ['content_id'], unique=True)
    op.drop_column('actresses', 'fanza_id')
    op.add_column('series', sa.Column('content_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_series_fanza_id'), table_name='series')
    op.create_index(op.f('ix_series_content_id'), 'series', ['content_id'], unique=True)
    op.drop_column('series', 'fanza_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('fanza_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_series_content_id'), table_name='series')
    op.create_index(op.f('ix_series_fanza_id'), 'series', ['fanza_id'], unique=True)
    op.drop_column('series', 'content_id')
    op.add_column('actresses', sa.Column('fanza_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_actresses_content_id'), table_name='actresses')
    op.create_index(op.f('ix_actresses_fanza_id'), 'actresses', ['fanza_id'], unique=True)
    op.drop_column('actresses', 'content_id')
    # ### end Alembic commands ###
